### ISSUE TITLE
Unable to run `train/train_navigation.py`

### ISSUE THREAD

**Issue by mkb9559** [proroklab/HetGPPO#5]
Hi!

Thanks for your great work! Your demonstration is really interisting!

I have successfully run `train/train_flocking.py ` in accodance to your introduction, but I meet some troubles when running `train/train_navigation.py`. Here are the reported errors:

```
Failure # 1 (occurred at 2024-09-09_17-52-57)
Traceback (most recent call last):
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 1050, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\_private\worker.py", line 2291, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::MultiPPOTrainer.__init__()[39m (pid=9988, ip=127.0.0.1, repr=MultiPPOTrainer)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 139, in __init__
    self.add_workers(
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 490, in add_workers
    self.foreach_worker(lambda w: w.assert_healthy())
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 620, in foreach_worker
    remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\_private\worker.py", line 2291, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=13732, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001DB8A67DC40>)
  File "python\ray\_raylet.pyx", line 859, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 863, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 810, in ray._raylet.execute_task.function_executor
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 625, in __init__
    self._build_policy_map(
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1899, in _build_policy_map
    self.policy_map.create_policy(
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\policy\policy_map.py", line 134, in create_policy
    policy = create_policy_for_framework(
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\utils\policy.py", line 116, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
  File "C:\Users\lenovo\Desktop\HetGPPO-main\rllib_differentiable_comms\multi_trainer.py", line 427, in __init__
    TorchPolicyV2.__init__(
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\policy\torch_policy_v2.py", line 84, in __init__
    model, dist_class = self._init_model_and_dist_class()
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\policy\torch_policy_v2.py", line 452, in _init_model_and_dist_class
    model = ModelCatalog.get_model_v2(
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\models\catalog.py", line 622, in get_model_v2
    instance = model_cls(
  File "C:\Users\lenovo\Desktop\HetGPPO-main\models\gppo.py", line 487, in __init__
    self.trainer = cfg["trainer"]
KeyError: 'trainer'

During handling of the above exception, another exception occurred:

[36mray::MultiPPOTrainer.__init__()[39m (pid=9988, ip=127.0.0.1, repr=MultiPPOTrainer)
  File "python\ray\_raylet.pyx", line 852, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 906, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 859, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 863, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 810, in ray._raylet.execute_task.function_executor
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 414, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\tune\trainable\trainable.py", line 161, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\lenovo\.conda\envs\py39\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 549, in setup
    raise e.args[0].args[2]
KeyError: 'trainer'
```

And my enviroment is :
```
Package                   Version
------------------------- -----------
aiohappyeyeballs          2.4.0
aiohttp                   3.10.5
aiosignal                 1.3.1
async-timeout             4.0.3
attrs                     24.2.0
certifi                   2024.8.30
charset-normalizer        3.3.2
click                     8.0.4
cloudpickle               3.0.0
colorama                  0.4.6
contourpy                 1.3.0
cycler                    0.12.1
decorator                 4.4.2
distlib                   0.3.8
dm-tree                   0.1.8
docker-pycreds            0.4.0
filelock                  3.16.0
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.9.0
gitdb                     4.0.11
GitPython                 3.1.43
grpcio                    1.66.1
gym                       0.23.1
gym-notices               0.0.8
idna                      3.8
imageio                   2.35.1
imageio-ffmpeg            0.5.1
importlib_metadata        8.4.0
importlib_resources       6.4.4
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.7
lazy_loader               0.4
lz4                       4.3.3
MarkupSafe                2.1.5
matplotlib                3.9.2
moviepy                   1.0.3
mpmath                    1.3.0
msgpack                   1.0.8
multidict                 6.0.5
networkx                  3.2.1
numpy                     1.23.5
packaging                 24.1
pandas                    2.2.2
pillow                    10.4.0
pip                       24.2
platformdirs              4.3.2
proglog                   0.1.10
protobuf                  5.28.0
psutil                    6.0.0
pyglet                    1.5.27
pyparsing                 3.1.4
python-dateutil           2.9.0.post0
pytz                      2024.1
PyYAML                    6.0.2
ray                       2.1.0
referencing               0.35.1
requests                  2.32.3
rpds-py                   0.20.0
scikit-image              0.24.0
scikit-learn              1.5.1
scipy                     1.13.1
sentry-sdk                2.13.0
setproctitle              1.3.3
setuptools                73.0.1
six                       1.16.0
smmap                     5.0.1
sympy                     1.13.2
tabulate                  0.9.0
tensorboardX              2.6.2.2
threadpoolctl             3.5.0
tifffile                  2024.8.30
torch                     2.4.1
torch_geometric           2.5.3
tqdm                      4.66.5
typing_extensions         4.12.2
tzdata                    2024.1
urllib3                   2.2.2
virtualenv                20.26.4
vmas                      1.2.12
wandb                     0.17.9
wheel                     0.44.0
yarl                      1.11.0
zipp                      3.20.1
```

Thanks for your altruistic help!

**Comment by matteobettini** [comment]
Now it should work

**Comment by mkb9559** [comment]
Yes, it works. Thank for you agagin.
